# Set environment variables
#export RESOURCE_GROUP?=swarm-cluster
#export RESOURCE_GROUP=$(NAMESPACE_PREFIX)-common
#export TIMESTAMP=`date "+%Y-%m-%d-%H-%M-%S"`

# Permanent local overrides
#-include .env

# Create Zip package
default:
	zip -r myAppFiles.zip .
